@echo off
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=16_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=16_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=16_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=16_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=16_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=16_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=16_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=16_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=16_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=16_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=16_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=16_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=16_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=16_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=16_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=16_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=16_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=16_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=16_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=16_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=16_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=16_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=16_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=16_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=16_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=16_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=16_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=16_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=16_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=16_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=32_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=32_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=32_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=32_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=32_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=32_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=32_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=32_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=32_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=32_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=32_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=32_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=32_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=32_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=32_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=32_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=32_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=32_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=32_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=32_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=32_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=32_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=32_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=32_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=32_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=32_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=32_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=32_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=32_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=32_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=64_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=64_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=64_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=64_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=64_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=64_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=64_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=64_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=64_lr=0.001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=64_lr=0.001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=64_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=64_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=64_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=64_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=64_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=64_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=64_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=64_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=64_lr=0.0001.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=64_lr=0.0001.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=1_bs=64_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=2_bs=64_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=3_bs=64_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=4_bs=64_lr=1e-05.json
python train.py --config ./configs/birnn/BiDeepRNN_layers=5_bs=64_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=1_bs=64_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=2_bs=64_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=3_bs=64_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=4_bs=64_lr=1e-05.json
python train.py --config ./configs/deeprnn/DeepRNN_layers=5_bs=64_lr=1e-05.json